# Generates a C++ header embedding a file as a byte array.
#
# Usage:
#   cmake -DINPUT=<file> -DOUTPUT=<header> -DSYMBOL=<identifier> -P EmbedFile.cmake
#
# The header defines:
#   constexpr unsigned char <SYMBOL>[] = { ... };
#   constexpr size_t <SYMBOL>Size = sizeof(<SYMBOL>);

if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
    message(FATAL_ERROR "EmbedFile.cmake requires -DINPUT, -DOUTPUT and -DSYMBOL.")
endif()

file(READ "${INPUT}" hex_content HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex_content}")
# 16 bytes per line to keep the generated file diffable and editor-friendly.
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" bytes "${bytes}")

get_filename_component(input_name "${INPUT}" NAME)
file(WRITE "${OUTPUT}"
"// Auto-generated by cmake/EmbedFile.cmake from ${input_name}. Do not edit.
#pragma once

#include <cstddef>

constexpr unsigned char ${SYMBOL}[] = {
${bytes}
};
constexpr size_t ${SYMBOL}Size = sizeof(${SYMBOL});
")
